---
# Common configuration for all the nodes in the cluster.

- name: hostname configuration
  block:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      tags:
        - bootstrap

    - name: Update hostname in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.2\s.*'
        line: '127.0.0.2	{{ inventory_hostname }}'
      tags:
        - bootstrap

    - name: Add cluster mappings to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^{{ hostvars[item]['ansible_host'] }}"
        line: "{{ hostvars[item]['ansible_host'] }}	{{ hostvars[item]['inventory_hostname'] }}"
      loop: "{{ groups['all'] }}"
      tags:
        - bootstrap

# Apt sources
- name: Configure apt sources
  block:
    - name: apt sources | remove default sources.list
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent
      tags:
        - bootstrap

    - name: apt sources | enable main, contrib and non-free components on Debian
      ansible.builtin.apt_repository:
        repo: deb https://deb.debian.org/debian {{ item }} main contrib non-free
        state: present
        filename: main
      loop:
        - "{{ ansible_distribution_release }}"
        - "{{ ansible_distribution_release }}-updates"
        - "{{ ansible_distribution_release }}-backports"
      tags:
        - bootstrap
        - debian
      when:
        ansible_distribution == "Debian"

    - name: apt sources | enable main, contrib and non-free components for debian-security on Debian
      ansible.builtin.apt_repository:
        repo: deb https://deb.debian.org/debian-security/ {{ ansible_distribution_release }}-security main contrib non-free
        state: present
        filename: main
      tags:
        - bootstrap
        - debian
      when:
        ansible_distribution == "Debian"

    - name: Install bootstrap dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg

      tags:
        - bootstrap
        - dependencies

    # See README.md note ^2
    - name: Create the /etc/apt/keyrings directory if it does not exist
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags:
        - bootstrap
        - debian
        - ubuntu
      when:
        (ansible_distribution == "Debian" and ansible_distribution_major_version|int < 12) or
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 22)

# TODO: Move this task to a different role to allow choosing between different container runtimes
# containerd
- name: Configure and Install containerd from upstream (docker.com)
  block:
    - name: Containerd | Register dpkg architecture
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      register: dpkg_architecture
      changed_when: false
      tags:
        - bootstrap
        - containerd

    - name: Containerd | Download and install gpg key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://download.docker.com/linux/debian/gpg |\
          gpg --dearmor --output /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg
      tags:
        - bootstrap
        - containerd

    - name: Containerd | Add docker apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release }} stable
        state: present
        filename: docker
      tags:
        - bootstrap
        - containerd

    - name: Containerd | Install containerd.io package
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        default_release: "{{ ansible_distribution_release }}"
      loop:
        - containerd.io
      tags:
        - bootstrap
        - containerd

  when:
    - install_containerd_from_upstream is true


- name: Containerd | Install containerd package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - containerd
  tags:
    - bootstrap
    - containerd
  when:
    - install_containerd_from_upstream is false

# Note:
# 1. I'm intentionally not uninstalling any package manually in order to avoid conflicts, as I prefer to relay on Debian for do that.
#
#
- name: Containerd | Set configuration
  ansible.builtin.copy:
    src: files/etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: containerd_configuration
  tags:
    - bootstrap
    - containerd
    - config

- name: Containerd | Restart containerd runtime to reload configuration
  ansible.builtin.systemd:
    state: restarted
    name: containerd
  when: containerd_configuration.changed
  tags:
    - bootstrap
    - containerd
    - config

- name: Enable IPv4 forwarding and let iptables see bridged traffic
  block:
  - name: Configure kernel modules to be loaded
    community.general.modprobe:
      name: "{{ item }}"
      persistent: present
    loop: "{{ kernel_modules }}"
    notify:
      Load kernel modules
    tags:
      - bootstrap
      - kernel
      - k8s

  - name: Save sysctl params
    ansible.posix.sysctl:
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true
      name: "{{ item.key }}"
      value: "{{ item.value }}"
    loop: "{{ sysctl_parameters | dict2items }}"
    tags:
      - bootstrap
      - k8s
      - sysctl
